# # Default colors
# [colors.primary]
# background = '#0A0E14'
# foreground = '#B3B1AD'
#
# # Normal colors
# [colors.normal]
# black   = '#01060E'
# red     = '#EA6C73'
# green   = '#91B362'
# yellow  = '#F9AF4F'
# blue    = '#53BDFA'
# magenta = '#FAE994'
# cyan    = '#90E1C6'
# white   = '#C7C7C7'
#
# # Bright colors
# [colors.bright]
# black   = '#686868'
# red     = '#F07178'
# green   = '#C2D94C'
# yellow  = '#FFB454'
# blue    = '#59C2FF'
# magenta = '#FFEE99'
# cyan    = '#95E6CB'
# white   = '#FFFFFF'

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 0.95
startup_mode = "Windowed"
